#!/bin/bash
# Given a prompt and/or an input image, the model will generate a new image.

create_image() {
	URL="https://api.openai.com/v1/images/generations"
	SIZE="512x512"
	REQUEST_HEADERS=$(echo "{\"prompt\": \"${USER_PROMPT_TRANSFORMED}\", \
		\"size\": \"${SIZE}\"}" | sed 's/\t//g')
}

## Create image : Creates an image given a prompt.
#CREATE_IMAGE="curl https://api.openai.com/v1/images/generations \
#  -H 'Content-Type: application/json' \
#  -H 'Authorization: Bearer ${API_KEY}' \
#  -d '{
#  \"prompt\": \"${USER_PROMPT}\", # A text description of the desired image(s). The maximum length is 1000 characters.
#  \"n\": \"${IMAGES_NUMBER}\", # facultative : The number of images to generate. Must be between 1 and 10.
#  \"size\": \"${SIZE}\", # facultative :  The size of the generated images. Must be one of 256x256, 512x512, or 1024x1024.
#  \"response_format\": \"${RESPONSE_FORMAT}\", # facultative : The format in which the generated images are returned. Must be one of url or b64_json.
#  \"user\": \"${USER_ID}\", # facultative : A unique identifier representing your end-user, which can help OpenAI to monitor and detect abuse.
#}'"
#
## Create an image edit : Creates an edited or extended image given an original image and a prompt.
#CREATE_IMAGE_EDIT="curl https://api.openai.com/v1/images/edits \
#  -H 'Authorization: Bearer ${API_KEY}' \
#  -F image='@${IMAGE_TO_EDIT}' \ # The image to edit. Must be a valid PNG file, less than 4MB, and square. If mask is not provided, image must have transparency, which will be used as the mask.
#  -F prompt=\"${USER_PROMPT}\" \ # A text description of the desired image(s). The maximum length is 1000 characters.
#  -F mask='@${IMAGE_MASK}' \ # facultative : An additional image whose fully transparent areas (e.g. where alpha is zero) indicate where image should be edited. Must be a valid PNG file, less than 4MB, and have the same dimensions as image.
#  -F n=${IMAGE_TO_GENERATE_NUMBER} \ # facultative : The number of images to generate. Must be between 1 and 10.
#  -F size=\"${SIZE}\" \ # facultative : The size of the generated images. Must be one of 256x256, 512x512, or 1024x1024.
#  -F response_format=\"${RESPONSE_FORMAT}\" \ # facultative : The format in which the generated images are returned. Must be one of url or b64_json.
#  -F user=\"${USER_ID}\" \ # facultative : A unique identifier representing your end-user, which can help OpenAI to monitor and detect abuse.
#}'"
#
## Create image variation : Creates a variation of a given image.
#CREATE_IMAGE_VARIATION="curl https://api.openai.com/v1/images/variations \
#  -H 'Authorization: Bearer ${API_KEY}' \
#  -F image='@${IMAGE_TO_USE}' \ # The image to use as the basis for the variation(s). Must be a valid PNG file, less than 4MB, and square.
#  -F n=${_NUMBER} \ # facultative : The number of images to generate. Must be between 1 and 10.
#  -F size=\"${SIZE}\" # facultative : The size of the generated images. Must be one of 256x256, 512x512, or 1024x1024.
#  -F response_format=\"${RESPONSE_FORMAT}\" # facultative : The format in which the generated images are returned. Must be one of url or b64_json.
#  -F user=\"${USER_ID}\" # facultative : A unique identifier representing your end-user, which can help OpenAI to monitor and detect abuse.
#"

#REFERENCE : https://beta.openai.com/docs/api-reference/embeddings
