#!/bin/bash

debug_on() {
	DEBUG=true
	DEBUG_CB_FUNC="${_RED} && echo chatbash function : \${FUNCNAME[0]}"
	DEBUG_API_FUNC="${_RED} && echo api function : \${FUNCNAME[0]}"
	DEBUG_END="${_RESET} && echo ''"
	eval ${DEBUG_CB_FUNC}
	echo "Debug mode = true"
	eval ${DEBUG_END}
}
