#!/bin/bash

set_request_headers() {
	if [[ -z "$REQUEST_HEADERS" ]]; then
		if [[ -z $USER_IMAGE ]]; then
			REQUEST_HEADERS=$(echo "{\"model\": \"${MODEL}\", \
				\"prompt\": \"${USER_PROMPT_TRANSFORMED}\", \
				\"temperature\": ${TEMPERATURE}, \
				\"max_tokens\": ${MAX_TOKENS}}" | sed 's/\t//g')
		else
			create_image
		fi
		if [[ ${DEBUG} = true ]]; then
			eval ${DEBUG_CB_FUNC}
			echo -e "Request headers : ${REQUEST_HEADERS}"
			eval ${DEBUG_END}
		fi
	else
		if [[ ${DEBUG} = true ]]; then
			eval ${DEBUG_CB_FUNC}
			echo -e "Request headers ALREADY DEFINED : ${REQUEST_HEADERS}"
			eval ${DEBUG_END}
		fi
	fi
}
